### ISSUE TITLE
The kpoint symmetry and band plotting cleanup issue

### ISSUE THREAD

**Issue by mfherbst** [mfherbst/DFTK.jl#533]
Some points to cleanup left after #496 is merged

### Quick n' easy
- [x] Drop enforcing `pymatgen` installation (also from the docs) (#534)
- [x] `high_symmetry_kpath` does not use atomic units (#536)
- [x] `plot_bandstructure` does not use atomic units consistently (#536)
- [x] `plot_bandstructure` interface is quirky for linear Hamiltonians (#536)

### Cleanup
- [x] Use `Spglib` and retire direct use of `spglib_jll` (#876)
- [x] Merge `spglib_standardize_cell` and `get_spglib_lattice` (#568)
- [x] Drop kpoint duplication (#555)
- [x] Band structures also for supercells (#555)
- [x] Use `Brillouin.jl` in `high_symmetry_kpath` also for 1D and 2D lattices (#555)
- [ ] Integrate more with `Brillouin.jl` for BZ plots or band structure plots (see also #503)

### Consistency
- [ ] Take care of time-reversal symmetry / absence thereof consistently for kpath (see [this discussion](https://github.com/JuliaMolSim/DFTK.jl/pull/496#discussion_r725203554))
- [ ] Take care of spin / magnetic moments in cell standardisation and kpath generation

**Comment by jaemolihm** [comment]
Hi, I'm planning to make a PR to Brillouin.jl for a function that gives k path for arbitrary lattice vectors (https://github.com/thchr/Brillouin.jl/issues/13#issuecomment-968625017). After that, one can make `high_symmetry_kpath` in DFTK much simpler. Independently, I have a working branch that cleans up the kpath routines, e.g. deleting kpoint duplication. If nobody is working on these, I can pick it up and make a PR (after making a PR to Brillouin.jl).

**Comment by mfherbst** [comment]
@jaemolihm  Yes that would be highly appreciated! Noone is working on these at the moment. Thanks for your work on this (truly annoying) aspects of solid-state modelling!
